Unit 3 - Functions - Eddie Tong
Edison-Tong/fundamentals-first-solutions-Edison-Tong pull request #10
Opened 2024-07-24 18:25 UTC by Edison-Tong

![functions](https://github.com/user-attachments/assets/fef63afc-ae30-4d26-8eaf-833abe5268d4)

2024-07-24 22:45 UTC, AcquirEdge requested changes
Just one change to your quiz.

2024-07-24 22:45 UTC, AcquirEdge commented on Unit 3/functions/quiz.md
> +   Stand for DO NOT REPEAT meaning: make your code consise
Actually stands for Don't Repeat Yourself. Close, but please fix this.

2024-07-25 15:39 UTC, Edison-Tong commented
HA I don't know what I was thinking with that answer. I got it fixed now

2024-07-25 17:38 UTC, AcquirEdge approved these changes
Looks good!

2024-07-25 18:01 UTC, merged