Unit 6 - Dynamic content - Eddie Tong
Edison-Tong/fundamentals-first-solutions-Edison-Tong pull request #18
Opened 2024-08-04 00:58 UTC by Edison-Tong

![Screenshot 2024-08-03 at 6 50 02 PM](https://github.com/user-attachments/assets/15ddf6bb-b0da-49f9-a65c-5c009b7f7020)

2024-08-04 17:31 UTC, AcquirEdge requested changes
just one quiz question needs a review. Otherwise looks good.

2024-08-04 17:31 UTC, AcquirEdge commented on Unit 6/dynamic-content/quiz.md
> +$(".example").attr("class", "Exmple-text");
Not quite... We're changing text, not attributes here.

2024-08-05 20:44 UTC, Edison-Tong commented
whoops sorry I misread that I think.

2024-08-05 21:22 UTC, AcquirEdge approved these changes
Looks good!

2024-08-05 21:43 UTC, merged